name: React Native Build

on:
  push:
    branches: [ "main" ] # 可以根据需要修改触发分支
  pull_request:
    branches: [ "main" ]

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease
          
      - name: Upload Android Build
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: android/app/build/outputs/apk/release/
          
  ios-build:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install dependencies
        run: |
          yarn install
          cd ios && pod install
          
      - name: Build iOS
        run: |
          cd ios
          xcodebuild -workspace test_rn_github_workflow.xcworkspace -scheme test_rn_github_workflow -configuration Release -archivePath test_rn_github_workflow.xcarchive archive
          xcodebuild -exportArchive -archivePath test_rn_github_workflow.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
          
      - name: Upload iOS Build
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: ios/build/